"""add passes table

Revision ID: 497eb09287e0
Revises: 9c29ea7ac4d0
Create Date: 2026-04-15 16:38:41.157313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497eb09287e0'
down_revision: Union[str, Sequence[str], None] = '9c29ea7ac4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=False),
    sa.Column('to_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passes_from_user_id'), 'passes', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_passes_to_user_id'), 'passes', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passes_to_user_id'), table_name='passes')
    op.drop_index(op.f('ix_passes_from_user_id'), table_name='passes')
    op.drop_table('passes')
    # ### end Alembic commands ###
